services:
  postgres:
    image: postgres:15-alpine
    container_name: mgbds_postgres
    restart: always
    environment:
      POSTGRES_DB: mgbds_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
